"""City added to company

Revision ID: 0c462142cf8c
Revises: 9b85ef653063
Create Date: 2024-01-31 12:00:44.628771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c462142cf8c'
down_revision: Union[str, None] = '9b85ef653063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('company', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'city', ['city_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'city_id')
    op.drop_column('company', 'phone')
    # ### end Alembic commands ###
