"""added photo

Revision ID: 6f48f29017b4
Revises: af7543503083
Create Date: 2024-01-31 12:22:04.203548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f48f29017b4'
down_revision: Union[str, None] = 'af7543503083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'about_company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('company', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('company', 'about_company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
