"""empty message

Revision ID: 9efd3ff345f8
Revises: fbbfc760156f
Create Date: 2024-02-09 19:41:43.556957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efd3ff345f8'
down_revision: Union[str, None] = 'fbbfc760156f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('expectation', sa.String(), nullable=True))
    op.add_column('vacancy', sa.Column('conditions', sa.String(), nullable=True))
    op.alter_column('vacancy', 'min_salary',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('vacancy', 'working_conditions')
    op.drop_column('vacancy', 'candidate_expectation')
    op.drop_column('vacancy', 'about_company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('about_company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vacancy', sa.Column('candidate_expectation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vacancy', sa.Column('working_conditions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('vacancy', 'min_salary',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_column('vacancy', 'conditions')
    op.drop_column('vacancy', 'expectation')
    # ### end Alembic commands ###
